### ISSUE TITLE
Dependency upgrade

### ISSUE THREAD

**Issue by ledjon-behluli** [cezarypiatek/RoslynTestKit#20]
Consider upgrading to `Microsoft.CodeAnalysis.*` latest stable version, in case [issue-19](https://github.com/cezarypiatek/RoslynTestKit/issues/19) is fixed

**Comment by cezarypiatek** [comment]
There is no need to bump up those dependencies until the RoslynTestKit requires the newest API.
This issue with errors generated by NuGet can be solved by installing the latest package versions directly to the test project.
I'm sure it works because I have done that in a few of my projects. If you still have a problem with the nuget, please provide a repo link, I will try to take a look at that.

**Comment by ledjon-behluli** [comment]
Absolutely no issues with that. I just thought killing two birds with one stone since the latest stable release is 4.3.1 which should (theoretically) mean no breaking changes that would need further work on RoslynTestKit.

Anyway I am closing this issue.
